In [ ]:
import numpy as np
import pandas as pd
from sklearn import linear_model
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
# reading all the csv files
#------------x----------q1-------x---------------x------------x-----------------
print("-------------x------------q1------------x-------------x---------------x--")
df1=pd.read_csv(r'/users/prince/state_wise_crop_production.csv')
print(df1.head())
df2=pd.read_csv(r'/users/prince/crop_production.csv')
print(df2.head())
df3=pd.read_csv(r'/users/prince/cpdata.csv')
print(df3.head())
df4=pd.read_csv(r'/users/prince/cropproductiononvariousfactors.csv')
print(df4.head())
df5=pd.read_csv(r'/users/prince/cropph.csv')
print(df5.head())
print(df1.info())
print(df2.info())
print(df3.info())
print(df4.info())
print(df5.info())
# EDA - checking whether there are null values or not
print("null values in df1",df1.isnull().sum())
print("null values in df2",df2.isnull().sum())
print("null values in df3",df3.isnull().sum())
print("null values in df4",df4.isnull().sum())
print("null values in df5",df5.isnull().sum())
print("as df2 has 3730 null values in Production column so we will fill them with mean of the column")
# df2 has null values , so replacing them with mean  
df2.fillna(df2["Production"].mean(),inplace=True)
print("after filling the Null values,now check for the null values")
print("null values in df2",df2.isnull().sum())
e=df2
# storing the needed dataframes in other variables ,so that they won't be changed 
i=df1
# sort_values will sort the dataframe according to the passed column
i.sort_values("Yield (Quintal/ Hectare) ",ascending=False)
g=df1
# droping the duplicate values
g.drop_duplicates(subset="State",inplace=True)
g.drop(['Cost of Cultivation (`/Hectare) A2+FL','Cost of Cultivation (`/Hectare) C2','Cost of Production (`/Quintal) C2','Yield (Quintal/ Hectare) '],axis=1,inplace=True)
print("these crops are the best crops to grow in these states")
print(g)

df2['Yield']=(df2['Production']/df2['Area'])
o=df2
o.sort_values("Yield",inplace=True,ascending=False)
h=o
h.drop_duplicates(subset="State_Name",inplace=True)
h.drop(['District_Name','Crop_Year','Season','Area','Production','Yield'],axis=1,inplace=True)
print(h)

k=df4
k.sort_values("Production",inplace=True,ascending=False)
print(k)
j=k
j.drop_duplicates(subset="Crop",inplace=True)
t=j['Production']
j.drop(['Cropconversion','Production'],axis=1,inplace=True)
print("the factors affecting the most are")
print(j)
#------------x----------q2-------------x--------------------x-------------------
print("-----------x-----------------q2-------------x----------------x----------")
# shape func will tell about the no of rows and columns 
print("shapes of different dataframes ----->")
print(df1.shape)
print(df2.shape)
print(df3.shape)
print(df4.shape)
print(df5.shape)
df=df4
df.drop('Crop',axis=1,inplace=True)
print(df.isnull().sum())
# dtypes tell about the datatype of each column 
print("datatypes are ----->",df.dtypes)
# for training and testing -> we will split the data
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df,t,test_size=0.2)
from sklearn.ensemble import RandomForestRegressor
  # max_depth= depth of the trees
  # random_state ,if int then off
  #n_esti...= no of trees
reg=RandomForestRegressor(max_depth=7,random_state=42,n_estimators=58)
  # fitting the model
reg.fit(x_train,y_train)
  # predicted values
y_pred=reg.predict(x_test)
print("predicted values ---->",y_pred)

#-------------x--------------q3------------x-----------------x-------------x----
print("--------------x------------q3--------------------x---------------------x-")
e=pd.read_csv(r'/users/prince/crop_production.csv')
# filling the nan values with mean
e.fillna(e["Production"].mean(),inplace=True)
# it creates a new column named as 'Yield'
e['Yield']=(e['Production']/e['Area'])
o=e
o.sort_values("Yield",inplace=True,ascending=False)
n=o
n.drop_duplicates(subset="District_Name",inplace=True)
# unwanted features
n.drop(['State_Name','Crop_Year','Season','Area','Production','Yield'],axis=1,inplace=True)
print(n)
i=input("enter district name -->")
# using try and except - for q5 
try:
     # it will tell about that whether it has any true value or not
    t=(n['District_Name']==i).any()
     # if true then it will be executed 
    if t:
      h=n[n['District_Name']==i]
      print("Crop for district ",i," with index is",h['Crop'])
    else:
        # it will lead the control flow to the except block
        raise exception
except:
    print("entered district is not in the dataset")
#-------------x--------------q4------------x-----------------x-------------x----
print("--------------x------------q4--------------------x---------------------x-")
d=pd.read_csv(r'/users/prince/state_wise_crop_production.csv')
# new column as Cost 
d['Cost']=(d['Cost of Cultivation (`/Hectare) A2+FL']+d['Cost of Cultivation (`/Hectare) C2']+d['Cost of Production (`/Quintal) C2'])
# dropping the unwanted features
d.drop(['Cost of Cultivation (`/Hectare) A2+FL','Cost of Cultivation (`/Hectare) C2','Cost of Production (`/Quintal) C2'],axis=1,inplace=True)
d.sort_values(["Yield (Quintal/ Hectare) ","Cost"],inplace=True,ascending=False)
d.drop_duplicates(subset="State",inplace=True)
print(d)
i=input("enter state from the above table -->")
# using try and except - for q5 
try:
    # it will tell about that whether it has any true value or not
    t=(d['State']==i).any()
    # if true then it will be executed 
    if t:
       f=d[d['State']==i]
       print("suitable crop for ",i,"with index is",f['Crop'])
    else:
        # it will lead the control flow to the except block
        raise exception
except:
    print("entered state is not in the dataset")


#-------------x--------------q5------------x-----------------x-------------x----
print("--------------x------------q5--------------------x---------------------x-")
print("solution of ques 5 is done in above quetions ,if there is not a feature matching with the dataset values ,then it will tell the user about it.")
# using try and except the solution of q5 is already done in q3 and q4

#-------------x--------------q6------------x-----------------x-------------x----
print("--------------x------------q6--------------------x---------------------x-")
l=pd.read_csv(r'/users/prince/cropproductiononvariousfactors.csv')
l.sort_values("Production",inplace=True,ascending=False)
l.sort_values("Rainfall",inplace=True,ascending=True)
l.drop_duplicates(subset="Crop",inplace=True)
l.drop(['Rainfall','Temperature','Ph'],axis=1,inplace=True)
print("crops which are being grown by farmers ,producion and crop conversion are -->",l)

#-------------x--------------q7------------x-----------------x-------------x----
# as info about the soil health and cost associated with soil improvement both are not available , so I will be telling about the ph of the soil  
print("--------------x------------q7--------------------x---------------------x--------------------")
x=pd.read_csv(r'/users/prince/cropproductiononvariousfactors.csv')
x.sort_values("Production",inplace=True,ascending=False)
x.drop_duplicates(subset="Crop",inplace=True)
x.drop(['Rainfall','Temperature','Production'],axis=1,inplace=True)
print("ph of the soil should be this which is given in the following dataset,for prescribed crops-->",x)

#-------------x--------------q8------------x-----------------x-------------x----
print("--------------x------------q8--------------------x---------------------x-")
l=pd.read_csv(r'/users/prince/cropproductiononvariousfactors.csv')
p=l
p.sort_values("Production",inplace=True,ascending=False)
print(p)
m=p
m.drop_duplicates(subset="Crop",inplace=True)
d=m['Production']
q=l
q.drop(['Crop','Cropconversion'],axis=1,inplace=True)
print(q)

print("linear regression")
from sklearn.linear_model import LinearRegression
x_train,x_test,y_train,y_test=train_test_split(q,d,test_size=0.2,random_state=100)
reg=LinearRegression()
reg.fit(x_train,y_train)
print("score of linear regression in this project",(reg.score(x_test,y_test))*100)
# I've used multi regression in it because it has several independent variablesand one dependent variable

print("************ THE END *************")

-------------x------------q1------------x-------------x---------------x--
    Crop           State  Cost of Cultivation (`/Hectare) A2+FL  \
0  ARHAR   Uttar Pradesh                                9794.05
1  ARHAR       Karnataka                               10593.15
2  ARHAR         Gujarat                               13468.82
3  ARHAR  Andhra Pradesh                               17051.66
4  ARHAR     Maharashtra                               17130.55

   Cost of Cultivation (`/Hectare) C2  Cost of Production (`/Quintal) C2  \
0                            23076.74                            1941.55
1                            16528.68                            2172.46
2                            19551.90                            1898.30
3                            24171.65                            3670.54
4                            25270.26                            2775.80

   Yield (Quintal/ Hectare)
0                       9.83
1                       7.47
2                       9.59
3                       6.42
4                       8.72
                    State_Name District_Name  Crop_Year       Season  \
0  Andaman and Nicobar Islands      NICOBARS       2000  Kharif
1  Andaman and Nicobar Islands      NICOBARS       2000  Kharif
2  Andaman and Nicobar Islands      NICOBARS       2000  Kharif
3  Andaman and Nicobar Islands      NICOBARS       2000  Whole Year
4  Andaman and Nicobar Islands      NICOBARS       2000  Whole Year

                  Crop    Area  Production
0             Arecanut  1254.0      2000.0
1  Other Kharif pulses     2.0         1.0
2                 Rice   102.0       321.0
3               Banana   176.0       641.0
4            Cashewnut   720.0       165.0
   temperature   humidity        ph    rainfall label
0    20.879744  82.002744  6.502985  202.935536  rice
1    21.770462  80.319644  7.038096  226.655537  rice
2    23.004459  82.320763  7.840207  263.964248  rice
3    26.491096  80.158363  6.980401  242.864034  rice
4    20.130175  81.604873  7.628473  262.717340  rice
    Rainfall  Temperature   Ph   Crop  Production Cropconversion
0  400.15082         20.0  3.0  Bajra     0.00690          Bajra
1  400.16331         20.0  3.2  Bajra     0.00747          Bajra
2  400.16387         20.0  3.2  Bajra     0.00749          Bajra
3  400.17967         20.0  3.2  Bajra     0.00822          Bajra
4  400.19582         20.0  3.2  Bajra     0.00895          Bajra
           Crop   Ph
0         Bajra  3.0
1        Banana  6.5
2        Barley  3.0
3          Bean  5.5
4  Black pepper  6.4
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49 entries, 0 to 48
Data columns (total 6 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   Crop                                   49 non-null     object
 1   State                                  49 non-null     object
 2   Cost of Cultivation (`/Hectare) A2+FL  49 non-null     float64
 3   Cost of Cultivation (`/Hectare) C2     49 non-null     float64
 4   Cost of Production (`/Quintal) C2      49 non-null     float64
 5   Yield (Quintal/ Hectare)               49 non-null     float64
dtypes: float64(4), object(2)
memory usage: 2.4+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 246091 entries, 0 to 246090
Data columns (total 7 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   State_Name     246091 non-null  object
 1   District_Name  246091 non-null  object
 2   Crop_Year      246091 non-null  int64
 3   Season         246091 non-null  object
 4   Crop           246091 non-null  object
 5   Area           246091 non-null  float64
 6   Production     242361 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 13.1+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3100 entries, 0 to 3099
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   temperature  3100 non-null   float64
 1   humidity     3100 non-null   float64
 2   ph           3100 non-null   float64
 3   rainfall     3100 non-null   float64
 4   label        3100 non-null   object
dtypes: float64(4), object(1)
memory usage: 121.2+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 189232 entries, 0 to 189231
Data columns (total 6 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   Rainfall        189232 non-null  float64
 1   Temperature     189232 non-null  float64
 2   Ph              189232 non-null  float64
 3   Crop            189232 non-null  object
 4   Production      189232 non-null  float64
 5   Cropconversion  189232 non-null  object
dtypes: float64(4), object(2)
memory usage: 8.7+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58 entries, 0 to 57
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Crop    58 non-null     object
 1    Ph     58 non-null     float64
dtypes: float64(1), object(1)
memory usage: 1.0+ KB
None
null values in df1 Crop                                     0
State                                    0
Cost of Cultivation (`/Hectare) A2+FL    0
Cost of Cultivation (`/Hectare) C2       0
Cost of Production (`/Quintal) C2        0
Yield (Quintal/ Hectare)                 0
dtype: int64
null values in df2 State_Name          0
District_Name       0
Crop_Year           0
Season              0
Crop                0
Area                0
Production       3730
dtype: int64
null values in df3 temperature    0
humidity       0
ph             0
rainfall       0
label          0
dtype: int64
null values in df4 Rainfall          0
Temperature       0
Ph                0
Crop              0
Production        0
Cropconversion    0
dtype: int64
null values in df5 Crop    0
 Ph     0
dtype: int64
as df2 has 3730 null values in Production column so we will fill them with mean of the column
after filling the Null values,now check for the null values
null values in df2 State_Name       0
District_Name    0
Crop_Year        0
Season           0
Crop             0
Area             0
Production       0
dtype: int64
these crops are the best crops to grow in these states
         Crop           State
0       ARHAR   Uttar Pradesh
1       ARHAR       Karnataka
2       ARHAR         Gujarat
3       ARHAR  Andhra Pradesh
4       ARHAR     Maharashtra
6      COTTON          Punjab
9      COTTON         Haryana
10       GRAM       Rajasthan
11       GRAM  Madhya Pradesh
17  GROUNDNUT      Tamil Nadu
20      MAIZE           Bihar
25      MOONG          Orissa
32      PADDY     West Bengal
                         State_Name                   Crop
100325                       Kerala              Sugarcane
150198                       Odisha                   Ragi
168710                    Rajasthan                 Garlic
207817                Uttar Pradesh               Sannhamp
86001                     Karnataka               Cardamom
232313                  Uttarakhand                   Gram
115296               Madhya Pradesh            Castor seed
182313                   Tamil Nadu      Rapeseed &Mustard
53837                  Chhattisgarh              Coriander
66268                       Haryana                  Onion
241586                  West Bengal              Arhar/Tur
6543                 Andhra Pradesh            Castor seed
19096                         Assam                Tobacco
161198                   Puducherry                Sesamum
191981                   Telangana       Rapeseed &Mustard
74684            Jammu and Kashmir          other oilseeds
72437              Himachal Pradesh                Sesamum
31017                         Bihar                Sesamum
57094                           Goa              Groundnut
11285             Arunachal Pradesh               Turmeric
163866                       Punjab              Sugarcane
142828                      Mizoram  Peas & beans (Pulses)
138285                      Manipur  Peas & beans (Pulses)
51      Andaman and Nicobar Islands           Dry chillies
45912                    Chandigarh              Arhar/Tur
59353                       Gujarat           Dry chillies
128003                  Maharashtra     Other  Rabi pulses
146536                     Nagaland      Moong(Green Gram)
56690        Dadra and Nagar Haveli               Coconut
75636                     Jharkhand                 Potato
197446                      Tripura              Sugarcane
140996                    Meghalaya             Dry ginger
177431                       Sikkim                  Maize
          Rainfall  Temperature   Ph               Crop  Production  \
156677  1330.00000       31.000  7.5          Sugarcane   955.75034
156676  1320.00000       31.000  7.5          Sugarcane   907.89016
156675  1310.00000       31.000  7.5          Sugarcane   865.32060
156674  1300.00000       31.000  7.5          Sugarcane   842.22092
156673  1290.00000       31.000  7.5          Sugarcane   821.44347
...            ...          ...  ...                ...         ...
57458    400.05866       18.000  6.0              Jowar     0.00117
52622    100.01130       25.010  5.0          Guar seed     0.00113
86452    600.06506       21.005  6.3  Moong(Green Gram)     0.00081
86451    600.04113       21.000  6.3  Moong(Green Gram)     0.00051
52621    100.00340       25.000  5.0          Guar seed     0.00034

           Cropconversion
156677          Sugarcane
156676          Sugarcane
156675          Sugarcane
156674          Sugarcane
156673          Sugarcane
...                   ...
57458               Jowar
52622           Guar seed
86452   Moong(Green Gram)
86451   Moong(Green Gram)
52621           Guar seed

[189232 rows x 6 columns]
the factors affecting the most are
          Rainfall  Temperature   Ph                   Crop
156677  1330.00000     31.00000  7.5              Sugarcane
103473   715.00000     25.00000  7.1                  Onion
104105  2140.00000     25.80000  6.6                 Papaya
30176    911.00000     27.00000  7.3                 Cotton
8309     626.00000     26.00000  7.2                 Banana
167642  1157.09700     30.00000  6.1                Tapioca
86449    755.00000     26.00000  6.0                  Mesta
137416   810.00000     23.00000  6.5               Sannhamp
167917   515.00000     20.00000  6.2                 Tomato
44095    740.00000     20.30000  7.5                 Grapes
37011   1634.00000     27.64522  6.3                 Ginger
166061  1224.00000     25.00000  6.1           Sweet potato
13661    564.00000     23.00000  6.1                Cabbage
84705    760.00000     29.70634  6.4                  Maize
171972  1730.00000     24.00000  6.6               Turmeric
13591    847.43119     24.00000  6.0                Brinjal
33884    718.00000     22.00600  6.5                 Garlic
65692    515.00000     31.22999  6.5                   Jute
67139   1048.00000     24.00000  6.5            Lady Finger
5221     744.01857     24.00000  5.3                  Bajra
134268  1480.00000     24.00000  7.4                   Rice
161959   620.00000     25.00000  6.3              Sunflower
64268    760.00000     26.00000  6.8                  Jowar
108441  2028.40244     21.00000  5.8              Pineapple
13967   1700.86291     30.00000  5.9               Cardamom
108439   534.00000     23.00000  7.0  Peas & beans (Pulses)
23117   1072.40000     24.50000  6.3               Chillies
148904   565.00000     25.00000  6.6               Soyabean
112242   381.01849     17.94100  5.6                 Potato
188378   706.68875     29.00000  5.8                  Wheat
115340   709.00000     25.00000  6.5                Raddish
181341   830.00000     32.00000  6.6                   Urad
103584   500.00000     20.45000  7.8                 Orange
119205  1010.00000     25.00000  6.0                   Ragi
23129    980.00000     28.00000  6.0              Colocosia
16855    160.20000     22.00000  6.5            Cauliflower
95892    790.00000     31.00000  6.8      Moong(Green Gram)
13980    810.23529     15.00000  6.0                 Carrot
13332    510.00000     25.50000  6.8           Bottle Gourd
145816   700.00000     23.00000  6.5                Sesamum
52619    645.00000     25.43001  6.1              Groundnut
13230   2468.00000     27.00000  6.2           Black pepper
12343    989.53069     24.00000  5.2                 Barley
26061    916.00000     25.00000  8.5              Coriander
71175    596.00000     21.72063  6.0                Linseed
53838    210.00000     26.01000  6.2              Guar seed
43985    734.00000     24.34386  5.8                   Gram
16839    758.53571     24.00000  6.5            Castor seed
30689    952.00000     31.00000  6.0                 Cowpea
57456    810.29412     26.00000  6.4             Horse-gram
135465   800.00000     24.00000  6.3              Safflower
67022    610.00000     20.41400  7.0                Khesari
30747   1260.00000     25.31667  6.5             Drum Stick
181392  1615.22700     28.00000  5.9                 Varagu
12363    440.00000     24.00000  5.5                   Bean
13324    701.89781     26.00000  6.2              Blackgram
96498    620.00000     27.00000  7.5                   Moth
67171    627.27273     17.50000  6.9                 Lentil
-----------x-----------------q2-------------x----------------x----------
shapes of different dataframes ----->
(13, 2)
(33, 2)
(3100, 5)
(58, 4)
(58, 2)
Rainfall       0
Temperature    0
Ph             0
dtype: int64
datatypes are -----> Rainfall       float64
Temperature    float64
Ph             float64
dtype: object
predicted values ----> [ 90.13480356   6.02089594  14.94843148  18.66762501 245.40891164
  18.90179087  11.77833984  10.45463232  49.5493273  110.8402175
  19.03971956  11.16038815]
--------------x------------q3--------------------x---------------------x-

             District_Name       Crop
100325           KOZHIKODE  Sugarcane
100627          MALAPPURAM  Sugarcane
101658  THIRUVANANTHAPURAM  Sugarcane
101871            THRISSUR  Sugarcane
98558            ERNAKULAM  Sugarcane
...                    ...        ...
76143                GUMLA     Potato
74381            GANDERBAL     Potato
191872           HYDERABAD       Rice
75233               RAMBAN      Wheat
131395              MUMBAI      Maize

[646 rows x 2 columns]